options:
  merge-default-rules: true
rules:
  leading-zero: 0
  quotes:
    - 1
    - style: double
  no-color-literals: 0
  no-css-comments: 0
  class-name-format:
    - 0
  no-transition-all: 0
  force-element-nesting: 0
  no-vendor-prefixes: 0
